admins: ["admin"] #用户名写到这里，会成为系统管理员
salt: "e84d0755dda7a538315ea7a95a8c36af"
register: true #如果不想其他人注册，可以设置为false
showDurationMin: 30 #展示曲线的时间范围，单位为分钟
keepDurationHour: 24  #api探测结果在数据库保存的时间范围，单位为小时
idc:
    - "default" #将探测目标分配给哪个机房，agent组件也有一个对应的配置
http:
    listen: "0.0.0.0:1984"
    secret: "secret"
rpc:
    listen: "0.0.0.0:1985"
mysql:
    addr: "root:urlooker.pass@tcp(127.0.0.1:3306)/urlooker?charset=utf8&&loc=Asia%2FShanghai"
    idle: 10
    max: 20
ldap:
    enabled: false
    addr: "ldap.example.com:389"
    baseDN: "dc=example,dc=com"
    bindDN: "cn=mananger,dc=example,dc=com"
    bindPasswd: "12345678"
    userField: "uid"
    attributes: ["sn","mail","telephoneNumber"]
alarm: #告警判断组件，为true表示使用alarm组件
    enable: true 
    batch: 200
    replicas: 500
    connTimeout: 1000
    callTimeout: 5000
    maxConns: 32
    maxIdle: 32
    sleepTime: 30
    cluster:
        node-1: "127.0.0.1:1986"
falcon: #为 true 表示要向 falcon 或者 nightingale 推送数据
    enable: false
    addr: "http://transfer.addr/api/push"
    interval: 60
statsd:
    enable: false
    addr: "ip:port"
prom: 
    enable: false
    addr: "ip:port"


