admins: ["admin"] #用户名写到这里，会成为系统管理员
salt: "e84d0755dda7a538315ea7a95a8c36af"
register: true #如果不想其他人注册，可以设置为false
showDurationMin: 30 #展示曲线的时间范围，单位为分钟
keepDurationHour: 12  #api探测结果在数据库保存的时间范围，单位为小时
http:
    listen: "0.0.0.0:1984"
    secret: "secret"
rpc:
    listen: "0.0.0.0:1985"
mysql:
    addr: "root:123456@tcp(127.0.0.1:3306)/urlooker?charset=utf8&&loc=Asia%2FShanghai"
    idle: 10
    max: 20
ldap:
    enabled: false
    addr: "ldap.example.com:389"
    baseDN: "dc=example,dc=com"
    bindDN: "cn=mananger,dc=example,dc=com"
    bindPasswd: "12345678"
    userField: "uid"
    attributes: ["sn","mail","telephoneNumber"]
alarm: #告警判断组件，为true表示使用alarm组件
    enable: true 
    batch: 200
    replicas: 500
    connTimeout: 1000
    callTimeout: 5000
    maxConns: 32
    maxIdle: 32
    sleepTime: 30
    cluster:
        node-1: "127.0.0.1:1986"
monitorMap:
    default: ["hostname1"] #数组中的字符串需要和agent所在机器的hostname相同
    idc1: ["hostname.2"]
falcon: #open-falcon接收数据的地址，为true表示要向falcon推送数据
    enable: true
    addr: "http://falcon.transfer.addr/api/push"
    interval: 60
internalDns: #如果为true，表示使用自己的dns解析来解析域名
    enable: false
    cmd: "./script/dsn.sh"